def sum(a,b):
    c=a+b
    return c
a=2
b=3
c=sum(a,b)
print(c)

#RUN --> START DEBUGGINF
#ADD BREAKPOINT
#USE STEP INTO TO SEE FUNCTION IN ACTION
#USE CONTINUE FOR SIMPLE RUN WITHOUT SEEING FUNTION IN ACTION